---
# defaults file for osp.servers
cloud: ospcloud
state: present
image: rhel-guest
flavor: m2.small
key_name: ansible_ssh
int_net: int_network
ext_net: ext_network
userdata: |
  #!/bin/bash
  curl -o /tmp/openstack.pub \
  {{ vault_repo_url }}/openstack_keys/openstack.pub
  cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  curl -o /tmp/internal.repo {{ vault_repo_url }}/repo/internal.repo
  cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
