---
- name: Create new instances with network details and metadata
  os_server:
    name: "{{ item.value.name }}"
    state: "{{ item.value.state | default(state) }}"
    cloud: "{{ item.value.cloud | default(cloud) }}"
    image: "{{ item.value.image | default(image) }}"
    flavor: "{{ item.value.flavor | default(flavor) }}"
    key_name: "{{ item.value.key_name | default(key_name) }}"
    security_groups: "{{ item.value.security_group }}"
    meta:
      group: "{{ item.value.meta.group }}"
      deployment_name: "{{ item.value.meta.deployment_name }}"
    wait: true
    nics:
      - net-name: "{{ int_net }}"
    userdata: "{{ item.value.userdata | default(userdata) }}"


- name: Ensure server is started
  os_server_action:
    server: "{{ item.value.name }}"
    action: start


- name: Add floating IP to Servers
  os_floating_ip:
    server: "{{ item.value.name }}"
    state: "{{ item.value.state }}"
    cloud: "{{ cloud }}"
    network: "{{ ext_net }}"
    timeout: 360
    reuse: true
    wait: true
  register: f_ip


- name: Wait for server to be available
  wait_for:
    host: "{{ f_ip.floating_ip.floating_ip_address }}"
    port: 22
    timeout: 600
    search_regex: OpenSSH
  delegate_to: "{{ inventory_hostname }}"
