---
- name: Fetch Instance Info
  os_server_facts:
    cloud: ospcloud
    region_name: RegionOne
  register: result

- name: Add hosts
  add_host:
    name: "{{item.public_v4}}"
    ansible_ssh_private_key_file: "{{vault_key_path}}"
    ansible_ssh_user: "{{vault_ansible_user}}"
    repo_url: "{{vault_repo_url}}"
    groups:
      - "{{item.metadata.group}}"
      - "{{item.metadata.deployment_name}}"
    ansible_ssh_common_args: >
      -o ProxyCommand="ssh -i {{vault_key_path}} -W %h:%p {{vault_ansible_user}}@{{vault_ansible_host}}"
  loop: "{{result.ansible_facts.openstack_servers}}"
