---
- name: Create the tower credentials file
  template:
    src: tower_cli.j2
    dest: "~/tower_cli.cfg"

- name: Create Homework Assignment project 
  tower_project:
    name: "{{ proj_name }}"
    organization: "{{ org_name }}"
    scm_type: git
    scm_update_on_launch: yes
    scm_url: "{{github_repo}}"
    tower_verify_ssl: no
    state: present

- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    organization: Default
    state: present
    kind: ssh
    ssh_key_data: "/root/.ssh/openstack.pem"
    tower_verify_ssl: no
    username: cloud-user

- name: Create Inventory
  command: |
    tower-cli inventory create -n "{{static_inventory_name}}" --organization "{{org_name}}"

- name: Create Group in static inventory 
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name {{group_name}}

- name: Add workstation host in tower_inventory 
  command: |
    tower-cli host create --inventory "{{static_inventory_name}}" --name "{{host_name}}"

- name: Associate workstation host to group 
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"

- name: Tower Creds key file
  tower_credential:
    name: "{{opentlc_cred_name}}"
    organization: Default
    state: present
    kind: ssh
    tower_verify_ssl: no
    ssh_key_data: "{{path_to_opentlc_key}}"
    username: "{{opentlc_login}}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent
