---
- name: Set up internal repo
  get_url:
    url: "{{repo_url}}/repo/internal.repo"
    dest: /etc/yum.repos.d/internal.repo
  when: hostvars['workstation'] is defined

- file:
    path: /etc/yum.repos.d/internal.repo
    state: absent
  when: hostvars['workstation'] is not defined
